### ISSUE TITLE
Instrucction for use without Netlify and Forestry

### ISSUE THREAD

**Issue by gulpa** [themefisher/persian-hugo#2]
Hi, 

Thanks @mehedi-sharif for all your precious work. I wanna use this theme only with github pages. I don't want use another services. Maybe another people wants the same thing.

Can you explain or add in the documentation how to use this theme without Netlify and Forestry?

**Comment by developer-evan** [comment]
Hello @gulpa 

Here is great documentation for doing this https://gohugo.io/hosting-and-deployment/hosting-on-github/

**Comment by developer-evan** [comment]
I am going to close this issue, if you fetch any more problem then feel free to re open or create a new issue. than you
